nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-changed.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-changed.js"

yarnPath: .yarn/releases/yarn-berry.cjs
